douban/book/urls.py
from django.conf.urls import url
from .views import book_list, book_show, book_collect, book_uncollect, search, jump, comment_delete


urlpatterns = [
    url(r'^index/$', book_list, name='book_list'),
    url(r'^showbook/(\d+)/$', book_show, name='book_contain'),
    url(r'^booklist/$', book_list, name='book_list'),
    url(r'^booklist/(\d+)/$', book_list, name='book_list_classify'),
    url(r'^booklist/(\d+)/(\d+)/$', book_list, name='book_list_sort'),
    url(r'^collect/(\d+)/$', book_collect, name='book_collect'),
    url(r'^uncollect/(\d+)/$', book_uncollect, name='book_uncollect'),
    url(r'^search/(.*)/$',search,name='search'),
    url(r'^jump/$',jump,name='jump'),
    url(r'^commentdelete/(?P<id>[0-9]+)/$',comment_delete,name='comment_delete'),
    # url(r'^get_label/(?P<obj_id>\d+)', twice_label_choice),
]

douban/douban/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from main import views as main_views
from users.views import ajax_val
from django.conf.urls.static import static
from django.conf import settings
import django.views.static
from douban.settings import BASE_DIR
import os
from django.conf.urls import handler404, handler500

urlpatterns = [

    # main 
    url(r'',include('main.urls')),

    # users
    url(r'^accounts/', include('users.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^ajax_val/', ajax_val, name='ajax_val'),

    # admin
    url(r'^admin/', admin.site.urls),

    #book
    url(r'^book/', include('book.urls')),

    #富文本编辑器
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'static/ueditor/(?P<path>.*)', django.views.static.serve, {'document_root': os.path.join(BASE_DIR, 'static', 'ueditor')}),

    #静态文件路径
    url(r'static/admin/(?P<path>.*)', django.views.static.serve, {'document_root': os.path.join(BASE_DIR, 'static', 'admin')}),
    url(r'css/(?P<path>.*)', django.views.static.serve, {'document_root': os.path.join(BASE_DIR, 'static', 'css')}),
    url(r'static/css/(?P<path>.*)', django.views.static.serve, {'document_root': os.path.join(BASE_DIR, 'static', 'css')}),
    url(r'images/(?P<path>.*)', django.views.static.serve, {'document_root': os.path.join(BASE_DIR, 'static', 'images')}),
    url(r'static/images/(?P<path>.*)', django.views.static.serve, {'document_root': os.path.join(BASE_DIR, 'static', 'images')}),
    url(r'js/(?P<path>.*)', django.views.static.serve, {'document_root': os.path.join(BASE_DIR, 'static', 'js')}),
    url(r'static/js/(?P<path>.*)', django.views.static.serve, {'document_root': os.path.join(BASE_DIR, 'static', 'js')}),
    url(r'font/(?P<path>.*)', django.views.static.serve, {'document_root': os.path.join(BASE_DIR, 'static', 'font')}),
    url(r'static/font/(?P<path>.*)', django.views.static.serve, {'document_root': os.path.join(BASE_DIR, 'static', 'font')}),
    url(r'media/book_img/(?P<path>.*)', django.views.static.serve, {'document_root': os.path.join(BASE_DIR, 'media', 'book_img')}),
    url(r'article_img/(?P<path>.*)', django.views.static.serve, {'document_root': os.path.join(BASE_DIR, 'media', 'article_img')}),
    url(r'head_img/(?P<path>.*)', django.views.static.serve, {'document_root': os.path.join(BASE_DIR, 'media', 'head_img')}),
    url(r'media/static/img/(?P<path>.*)', django.views.static.serve, {'document_root': os.path.join(BASE_DIR, 'media', 'static','img')}),

]

handler404 = main_views.page_not_found
handler500 = main_views.page_not_found

douban/main/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^write/',WriteArticle,name='WriteArticle'),
    url(r'^informationChange/',userInformation),
    url(r'^$',userPage, name='userPage'),
    url(r'^index/',userPage),
    url(r'^userArticleList/',userArticle,name='userArticle'),
    url(r'^delete/(?P<id>[0-9]+)/$',deleteArticle,name='deleteArticle'),
    url(r'^change/(?P<id>[0-9]+)/$',changeArticle,name='changeArticle'),
    url(r'^detail/(?P<id>[0-9]+)/$',article_detail,name='article_detail'),
    url(r'^comment/$',commentList,name='commentList'),
    url(r'^articleList/(?P<cate>[0-9]+)/(?P<page>[0-9]+)/$',articleCate,name='articleCate'),
    url(r'^shoucang/(?P<article_id>[0-9]+)/$',article_shoucang,name='article_shoucang'),
    url(r'^saveArticle/$',saveArticle,name='saveArticle'),
    url(r'^saveBook/$',display_book_collect,name='saveBook'),
    url(r'^delete/save/(?P<article_id>[0-9]+)/$',deleteSave,name='deleteSave'),
    url(r'^delete/comment/(?P<comment_id>[0-9]+)/$',deleteComment,name='deleteComment'),
    url(r'^search/article/$',searchArticle,name='searchArticle')
]

douban/main/models.py
from django.db import models
from DjangoUeditor.models import UEditorField
from users.models import User
from django.utils.html import strip_tags
from .storage import ImageStorage
import markdown


class Article(models.Model):
    category=(('小说','小说'),('散文','散文'),('感悟','感悟'),('新闻','新闻'),)
    title = models.CharField('标题',max_length=256)
    pub_date = models.DateTimeField('发表时间',auto_now_add=True)
    update_time = models.DateTimeField('更新时间',auto_now=True,null=True)
    content = UEditorField('内容',toolbars="full",upload_settings={"imageMaxSize":1204000},settings={},)
    author = models.ForeignKey(User,verbose_name="作者",default="",null=True,on_delete=models.SET_NULL)
    abstract = models.CharField('摘要',max_length=256,null=True,blank=True)
    article_cate = models.CharField('类别',max_length=5,choices=category,default='小说')
    views = models.PositiveIntegerField(default=0)
    image = models.ImageField('封面',upload_to='article_img',storage=ImageStorage())
    isHomeArticle = models.BooleanField('首页文章',default=False)
    isDisplay = models.BooleanField('文章展示',default=False)


    def save(self,*args,**kwargs):
        if not self.abstract:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                ])
            self.abstract = strip_tags(md.convert(self.content))[:54]
        super(Article,self).save(*args,**kwargs)
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = r"用户文章"
        verbose_name_plural = r"用户文章"

    
class comment_article(models.Model):
    content = models.CharField('内容',max_length=145)
    pub_date = models.DateTimeField('发表时间',auto_now_add=True)
    author = models.ForeignKey(User, default="")
    article = models.ForeignKey(Article,default="")
    class Meta:
        verbose_name = r"文章评论"
        verbose_name_plural = r"文章评论"
        
    

class article_save(models.Model):
    article = models.ForeignKey(Article,default="")
    user = models.ForeignKey(User,default="")
    time = models.DateTimeField('时间',auto_now_add=True)
    class Meta:
        verbose_name = r"文章收藏"
        verbose_name_plural = r"文章收藏"

douban/main/forms.py
from django import forms
from .models import Article,comment_article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title','content','article_cate','image']

class Comment_Article_Form(forms.ModelForm):
	class Meta:
		model = comment_article
		fields = ['content']

douban/main/views.py
from django.shortcuts import render
import json
from django.shortcuts import redirect
from users.models import User
from .forms import *
from .models import *
from django.db.models import Q
from book.models import Book, Collection
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.core.files.base import ContentFile
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
import logging
from django.core.paginator import EmptyPage
from django.shortcuts import render_to_response
from book.models import Comment as bookComment

def userPage(request):
    article_list = Article.objects.filter(isHomeArticle=True).order_by('-update_time')[:11]
    article_1 = article_list[:1]
    article_2 = article_list[1:2]
    article_3 = article_list[2:3]
    article_4 = article_list[3:4]
    article_5 = article_list[4:5]
    article_photo = article_list[5:7]
    article_list = article_list[7:11]
    logging.debug(article_1)

    back = {
        "book": {},
        'article_list': article_list,
        'article_photo': article_photo,
        'article_1': article_1,
        'article_2': article_2,
        'article_3': article_3,
        'article_4': article_4,
        'article_5': article_5,
    }
    books = Book.objects.all().order_by('-score')[:8]
    i = 0
    allBook = {}
    for book in books:
        i = i + 1
        count = Collection.objects.filter(book=book).count()
        allBook[str(i)] = {
            "id": book.id,
            "score": book.score,
            "cover": book.cover.url,
            "bookname": book.bookname,
            "loveCount": count,
        }
    logging.debug(allBook)
    back['book'] = allBook
    try:
        first = request.user.first_login
    except:
        return render(request, 'shouye.html', back)

    logging.debug("11111111111111111111")

    if first == True:
        return render(request, 'main/personal_change.html')

    return render(request, 'shouye.html', back)


def userInformation(request):
    if not request.user.is_authenticated():
        return redirect('/')
    if request.method == 'POST':
        user = User.objects.get(pk=request.user.id)
        user.name = request.POST['name']
        user.sex = request.POST['sex']
        user.motto = request.POST['motto']
        user.head_img = request.FILES['image']
        user.first_login = False
        user.save()
    else:
        return render(request, 'main/personal_change.html')
    return redirect('/')


def WriteArticle(request):
    if not request.user.is_authenticated():
        return redirect('/')
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return render(request, 'main/personal_center_write_article.html')
        else:
            return render(request, 'main/personal_center_write_article.html')
    else:
        return render(request, 'main/personal_center_write_article.html')


def userArticle(request):
    if not request.user.is_authenticated():
        return redirect('/')
    article_list = Article.objects.filter(author=request.user).order_by('-update_time')
    return render(request, 'main/personal_center_personal_article.html', {'article_list': article_list})


def deleteArticle(request, id):
    if not request.user.is_authenticated():
        return redirect('/')
    user = request.user
    article = Article.objects.get(id=id,author=user)
    comment = comment_article.objects.filter(article=article)
    article.delete()
    comment.delete()
    return redirect('/userArticleList/')


def changeArticle(request, id):
    if not request.user.is_authenticated():
        return redirect('/')
    article = Article.objects.get(id=id)
    if request.method == 'POST':
        form = ArticleForm(request.POST,request.FILES, instance=article)
        if form.is_valid():
            j = form.save(commit=False)
            j.save()
            return redirect('/userArticleList/')
    else:
        return render(request, 'main/personal_change_article.html', {'article': article})


def article_detail(request, id):
    art = Article.objects.get(id=id)
    art.increase_views()
    commentOfArticle = comment_article.objects.filter(article=art).order_by('-pub_date')
    if request.user.is_authenticated():
        shoucang_list = article_save.objects.filter(article=art)
        isSave = False
        for i in shoucang_list:
            if i.user == request.user:
                isSave = True

        if request.method == 'POST':
            commentForm = Comment_Article_Form(request.POST)
            if commentForm.is_valid():
                comment = commentForm.save(commit=False)
                comment.author = request.user
                comment.article = art
                comment.save()
        return render(request, 'main/article_contain.html',
                      {'isSave': isSave, 'article': art, 'commentOfArticle': commentOfArticle})
    else:
        return render(request, 'main/article_contain.html', {'article': art, 'commentOfArticle': commentOfArticle})


def commentList(request):
    articleCommentList = comment_article.objects.filter(author=request.user).order_by('-pub_date')
    bookCommentList = bookComment.objects.filter(owner_id=request.user.id).order_by('-createTime')
    return render(request, 'main/personal_center_comment.html', {
        'articleCommentList': articleCommentList,
        'bookCommentList':bookCommentList})


def articleCate(request, cate, page):
    if cate == '1':
        article_list = Article.objects.all().filter(isDisplay = True).order_by('-views')[:15]
    elif cate == '2':
        article_list = Article.objects.all().filter(isDisplay = True).order_by('-update_time')[:15]
    elif cate == '3':
        article_list = Article.objects.filter(isDisplay = True).filter(article_cate='小说').order_by('-update_time')[:15]
    elif cate == '4':
        article_list = Article.objects.filter(isDisplay = True).filter(article_cate='散文').order_by('-update_time')[:15]
    elif cate == '5':
        article_list = Article.objects.filter(isDisplay = True).filter(article_cate='感悟').order_by('-update_time')[:15]
    elif cate == '6':
        article_list = Article.objects.filter(isDisplay = True).filter(article_cate='新闻').order_by('-update_time')[:15]
    else:
        cate = '1'
    paginator = Paginator(article_list, 5)
    try:
        article_page = paginator.page(page)
    except:
        page = 1
        article_page = paginator.page(page)
    if not request.user.is_authenticated():
        if request.method == 'POST':
            message = '请登录后收藏!'
            return render(request, 'main/article_list.html',
                          {'message': message, 'cate': cate, 'article_page': article_page})
        return render(request, 'main/article_list.html', {'cate': cate, 'article_page': article_page})
    else:
        save_article = article_save.objects.filter(user=request.user)
        if request.method == 'POST':
            article_id = request.POST['article_id']
            article = Article.objects.get(pk=article_id)
            try:
                article_save.objects.filter(article=article).get(user=request.user)
                message = '请勿重复收藏！'
                return render(request, 'main/article_list.html',
                              {'cate': cate, 'article_page': article_page, 'save_article': save_article,
                               'message': message})
            except:
                isSave = article_save()
                isSave.user = request.user
                isSave.article = article
                isSave.save()
                return render(request, 'main/article_list.html',
                              {'cate': cate, 'article_page': article_page, 'save_article': save_article})
    return render(request, 'main/article_list.html',
                  {'cate': cate, 'article_page': article_page, 'save_article': save_article})


def article_shoucang(request, article_id):
    article = Article.objects.get(id=article_id)
    commentOfArticle = comment_article.objects.filter(article=article).order_by('-pub_date')
    if not request.user.is_authenticated():
        message = '请登录后收藏!'
        return render(request,'main/article_contain.html',{'article':article,'message':message})
    else:
        if request.method == 'POST':
            article_id = request.POST['article_id']
            article = Article.objects.get(pk=article_id)
            try:
                article_save.objects.filter(article=article).get(user=request.user)
                message = '请勿重复收藏！'
                return redirect('/detail/' + article_id + '/')
            except:
                isSave = article_save()
                isSave.user = request.user
                isSave.article = article
                isSave.save()
                return redirect('/detail/' + article_id + '/')


def saveArticle(request):
    if not request.user.is_authenticated():
        return redirect('/')
    save_list = article_save.objects.filter(user=request.user).order_by('-time')
    return render(request, 'main/personal_center_save_article.html', {'save_list': save_list})


def deleteSave(request, article_id):
    if not request.user.is_authenticated():
        return redirect('/')
    article = Article.objects.get(id=article_id)
    saveArticle = article_save.objects.get(article=article)
    saveArticle.delete()
    return redirect('/saveArticle/')

def deleteComment(request,comment_id):
    if not request.user.is_authenticated():
        return redirect('/')
    comment = comment_article.objects.get(pk=comment_id)
    comment.delete()
    return redirect('/comment/')



def display_book_collect(request):
    back = {
        "book":{},
    }
    allC = Collection.objects.filter(collector=request.user)
    books = {}
    i = 0

douban/main/templates/main/article_list.html
{% extends 'article_base.html' %}

{% block ul %}

					<input class="body_top_input" type="text" value="{{cate}}" style="display: none;">
					<ul class="body_top_nav_list">
						<li class="body_top_nav"><a class="body_top_nav_a" href="/articleList/1/1/">热门读刊</a><div style="display: none;" class="body_top_nav_arrow"><img src="/static/images/arrow_1_down.png" alt=""></div></li>
						<li class="body_top_nav"><a class="body_top_nav_a" href="/articleList/2/1/">最新读物</a><div style="display: none;" class="body_top_nav_arrow"><img src="/static/images/arrow_1_down.png" alt=""></div></li>
						<li class="body_top_nav"><a class="body_top_nav_a" href="/articleList/3/1/">小说</a><div style="display: none;" class="body_top_nav_arrow"><img src="/static/images/arrow_1_down.png" alt=""></div></li>
						<li class="body_top_nav"><a class="body_top_nav_a" href="/articleList/4/1/">散文</a><div style="display: none;" class="body_top_nav_arrow"><img src="/static/images/arrow_1_down.png" alt=""></div></li>
						<li class="body_top_nav"><a class="body_top_nav_a" href="/articleList/5/1/">感悟</a><div style="display: none;" class="body_top_nav_arrow"><img src="/static/images/arrow_1_down.png" alt=""></div></li>
						<li class="body_top_nav"><a class="body_top_nav_a" href="/articleList/6/1/">新闻</a><div style="display: none;" class="body_top_nav_arrow"><img src="/static/images/arrow_1_down.png" alt=""></div></li>
					</ul>
				
					
					


		{% endblock %}
				</div>

			</div>
		{% block content %}
			<div class="body_middle">
				<div class="body_middle_inner">
					<ul class="body_middle_article_page_1">
						{% for article in article_page %}
						<li class="body_middle_article">
							<div class="body_middle_article_left">
								<a href="/detail/{{article.id}}">
								<img src="/{{article.image}}" alt=""></a>
								
								
							</div>
							<div class="body_middle_article_right">
								<div class="body_middle_article_title"><a class="hhh" href="/detail/{{article.id}}">{{article.title}}</a></div>
								<span class="body_middle_article_author">{{article.author.name}}</span>
								<span class="body_middle_article_publishtime">{{article.update_time}}</span>
								<p class="body_middle_article_info">{{article.abstract}}……</p>
								
							</div>
							<div class="body_middle_article_more">
								<form action="." method="post">
									{% csrf_token %}
									<input type="hidden" id="article_id" name="article_id" value="{{article.id}}">
									<input class="body_middle_article_like" type="image" id="id_image" src="/static/images/love_white.png" alt="">
									{% for shoucang in save_article %}
									{% if shoucang.article == article %}
									<input class="body_middle_article_like" type="image" id="id_image" src="/static/images/grade_love.png" alt="">
									{% endif %}
									{% endfor %}
								</form>
								
							</div>
													</li>
						{% endfor %}
					</ul>
				</div>
				<div class="body_bottom_page">
					{% if article_page.has_previous %}
						<span class="last_page"><a href="/articleList/{{cate}}/{{article_page.previous_page_number}}/"> 上一页</a></span>
						{% else %}
						<span class="last_page"> 上一页</span>
						{% endif %}
						<span class="first_page"><a href="/articleList/{{cate}}/1/"> 首页</a></span>
						{% if article_page.has_next %}
						<span class="next_page"><a href="/articleList/{{cate}}/{{article_page.next_page_number}}"> 下一页</a></span>
						{% else %}
						<span class="next_page">下一页</span>
						{% endif %}
						<div class="last_page_tip" style="display: none;">已经是最后一页啦~</div>
						<div class="first_page_tip" style="display: none;">已经是第一页啦~</div>
					</div>
			</div>

			{% endblock %}
			

douban/main/templates/main/index.html
{% extends 'basemain.html' %}
{% block title %}个人主页{% endblock %}
{% block content %}
<a href="/write/">个人主页</a>
{% endblock %}

douban/main/templates/main/personal_center_write_article.html
{% extends 'user_base.html' %}

  {% block link %}
  <link rel="stylesheet" href="/static/css/font_csh.css">
  <link rel="stylesheet" href="/static/css/personal_center_write_article.css">
  <link rel="shortcut icon" href="/static/images/bitbug_favicon.ico">
  <link rel="stylesheet" href="/static/css/footer.css">
  <script type="text/javascript" src="/static/ueditor/ueditor.config.js"></script>
  <script type="text/javascript" src="/static/ueditor/ueditor.all.min.js"></script>
  {% endblock %}

{% block content %}


				<div class="personal_body_write_article">

                    <form action="." enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                       
					<div class="personal_body_write_title"><input name="title" maxlength="256" required id="id_title"  class="personal_body_write_title_input" value="#请在此添加标题" type="text"></div>
          <div class="personal_body_write_add_img">
            <input type="file" name="image" required id="id_image" >

          </div>

									<div class="personal_body_write_content">

                                         <script class="personal_body_write_content_text" id="id_content"   name="content"  style="display: inline-block;" type="text/plain">

 </script>
<script type="text/javascript">

    var id_content = UE.getEditor('id_content',{'initialFrameWidth': 600, 'initialFrameHeight': 300, 'serverUrl': '/ueditor/controller/?imageMaxSize=1204000&imagePathFormat=static%2Fimg%2F&filePathFormat=main%2Fstatic%2Fimg%2F'});
     id_content.ready(function(){

     });
</script></div>

						<div class="article_type">
						<select  name="article_cate" id="id_article_cate">
  <option value="小说" selected>小说</option>

  <option value="散文">散文</option>

  <option value="感悟">感悟</option>

  <option value="新闻">新闻</option>
</select>
</div>
<br>
<input class="personal_body_write_submit" type="submit" value="提交">


</form>
					</div> 	

{% endblock %}

{% block script %}

<script src="/static/js/jquery-3.2.1.min.js"></script>
<script src="/static/js/personal_center_write_article.js"></script>
{% endblock %}


				

douban/main/templates/main/personal_change_article.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>个人中心</title>
	<link rel="stylesheet" href="/static/css/font_csh.css">
	<link rel="stylesheet" href="/static/css/personal_center_write_article.css">
	<link rel="shortcut icon" href="/static/images/bitbug_favicon.ico">
	<link rel="stylesheet" href="/static/css/footer.css">
	<script type="text/javascript" src="/static/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="/static/ueditor/ueditor.all.min.js"></script>
</head>
<body>
	 <div class="container">
		<div class="container_inner">
			<div class="personal_nav">
			<a href="/">
			<img  class="personal_nav_logo" src="/static/images/logo_4.png" alt=""></a>
			<h3 class="personal_nav_title">{{ request.user.name }}的个人主页</h3>
			<div style="clear: both;"></div>
			</div>
			<div class="personal_body">

				<div class="personal_body_arrow_1"><img src="/static/images/write_article_arrow.png" alt=""></div>
			
				
				<div class="personal_body_perinfo">
					<div class="personal_bofy_perinfo_pic"><img src="/{{request.user.head_img}}" alt=""></div>
					<h6 class="personal_body_perinfo_name">{{ request.user.name }}</h6>
					<img class="personal_body_perinfo_sex" src="/static/images/sex_1.png" alt="">
					<a href="/informationChange/"><img class="personal_body_perinfo_write" src="/static/images/write_ar_2.png" alt=""></a>
					<div class="personal_body_perinfo_words">{{request.user.motto}}</div>
					</div>
					<div class="personal_body_menu">
					<ul>
						<li class="personal_body_save_books">
							<a href="{% url 'saveBook' %}">
								<span class="personal_body_save_books_span">我收藏的书籍</span>
								
								<img class="personal_body_save_books_img" src="/static/images/save_arrow_nochoose_1.png" alt="">
							</a>
						</li>
							<li class="personal_body_save_articles">
								<a href="/saveArticle/">
								<span class="personal_body_save_articles_span">我收藏的文章</span>
								
								<img class="personal_body_save_articles_img" src="/static/images/save_arrow_nochoose_1.png" alt="">
							</a>
						</li>
						<li class="personal_body_save_comment">
							<a href="/comment/">
								<span class="personal_body_save_comment_span">我编写的评论</span>
								
								<img class="personal_body_save_comment_img" src="/static/images/save_arrow_nochoose_1.png" alt="">
							</a>
						</li>
						<li class="personal_body_personal_article">
							<a href="/userArticleList/">
								<span class="personal_body_personal_article_span">我编写的文章</span>
								
								<img class="personal_body_personal_article_img" src="/static/images/save_arrow_nochoose_1.png" alt="">
							</a>
						</li>

					</ul>
				</div>

				<div class="personal_body_write">
						<a  class="personal_body_write_a" href="/write/">
						<span class="personal_body_write_span">我要写文章</span>
						<img  class="personal_body_write_img" src="/static/images/write_aticle_2.png" alt="">
					</a>
				</div>
				<div class="personal_body_write_article">

                    <form action="." method="post" enctype="multipart/form-data">
                        {% csrf_token %}
					<div class="personal_body_write_title"><input name="title" maxlength="256" required id="id_title"  class="personal_body_write_title_input" value="{{article.title}}" type="text"></div>
					<div class="personal_body_write_add_img">
            <input type="file" name="image" required id="id_image" >

          </div>

									<div class="personal_body_write_content">

                                         <script class="personal_body_write_content_text" id="id_content"   name="content"  style="display: inline-block;" type="text/plain">
                                         	{{article.content|safe}}

 </script>
<script type="text/javascript">

    var id_content = UE.getEditor('id_content',{'initialFrameWidth': 600, 'initialFrameHeight': 300, 'serverUrl': '/ueditor/controller/?imageMaxSize=1204000&imagePathFormat=static%2Fimg%2F&filePathFormat=main%2Fstatic%2Fimg%2F'});
     id_content.ready(function(){

     });
</script></div>

							<div class="article_type">
						<select  name="article_cate" id="id_article_cate">
  <option value="小说" selected>小说</option>

  <option value="散文">散文</option>

  <option value="感悟">感悟</option>

  <option value="新闻">新闻</option>
</select>
</div>
<input class="personal_body_write_submit" type="submit" value="提交">
</form>
					</div> 				
			
				</div>
			</div>
		</div>

		<div class="footer">
			<div class="footer_inner">
				<div class="footer_nav">
					<ul class="footer_nav_list">
						<li class="footer_nav_content_1"><a class="footer_nav_content_a_1" href="">关于我们</a></li>
						<li class="footer_nav_content_2"><a class="footer_nav_content_a_2"  href="">加入我们</a></li>
						<li class="footer_nav_content_3"><a class="footer_nav_content_a_3"  href="">合作伙伴</a></li>
						<li class="footer_nav_content_4"><a  class="footer_nav_content_a_4" href="">广告服务</a></li>
						<li class="footer_nav_content_5"><a class="footer_nav_content_a_5"  href="">常见问题</a></li>
					</ul>
				</div>
				<div class="footer_nav_middle">
					<ul class="footer_nav_middle_list">
						<li class="footer_nav_middle_xinlang"><a class="footer_nav_middle_a_xinlang" href=""><img src="/static/images/xinlang_lgo.png" alt=""></a></li>
						<li class="footer_nav_middle_wechat"><a class="footer_nav_middle_a_wechat" href=""><img src="/static/images/weixin_logo.jpg" alt=""></a></li>
						<li class="footer_nav_middle_chrome"><a class="footer_nav_middle_a_chrome" href=""><img src="/static/images/liulan——logo.png" alt=""></a></li>
					</ul>
					<div style="clear: both;"></div>
				</div>
				<div class="footer_bottom_address">© 2005－2018 douban.com, all rights reserved 北京豆网科技有限公司</div>
			</div>

		</div>
		
		
	</div>
	
</body>
<script src="/static/js/jquery-3.2.1.min.js"></script>
<script src="/static/js/personal_center_write_article.js"></script>
</html>